# Generated by Django 2.0.2 on 2018-06-24 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import way_video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallaryVideo',
            fields=[
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='video_owner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('content', models.ImageField(blank=True, null=True, upload_to=way_video.models.content_file_name)),
                ('style', models.ImageField(blank=True, null=True, upload_to=way_video.models.style_file_name)),
            ],
        ),
    ]
