# Generated by Django 2.0.2 on 2018-06-21 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('way_img', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallaryimg',
            name='id',
        ),
        migrations.AlterField(
            model_name='gallaryimg',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
