# Generated by Django 2.0.2 on 2018-06-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('way_img', '0002_auto_20180621_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallaryimg',
            name='res',
            field=models.ImageField(blank=True, null=True, upload_to='way_img/'),
        ),
    ]
