# Generated by Django 2.0.2 on 2018-06-23 18:50

from django.db import migrations, models
import way_img.models


class Migration(migrations.Migration):

    dependencies = [
        ('way_img', '0003_auto_20180622_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallaryimg',
            name='res',
        ),
        migrations.AlterField(
            model_name='gallaryimg',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to=way_img.models.content_file_name),
        ),
    ]
